### PR TITLE
Update ex_1811.cpp

### PR DESCRIPTION
**Pull request by hshams361**

### CODE REVIEW

**Comment by hshams361** [comment]
1- Function declarations in lines 28 and 31 ( **getNewWord** and **printGuesses** ) don't match with the corresponding function definitions in lines 113 and 139

2- line 114:
As you know, vector elements are indexed from **zero** to **_vector size - 1_**

Thanks

**Review by siidney — COMMENTED** [review]
Line 114: The +- 1 is unnecessary as rand() goes from 0 to wordList.size() - 1 anyway.
 
Lines 133-134: Missing brackets around the for loop.

Looks good though thanks.

**Comment by hshams361** [comment]
Good point :+1: Yes,you're right, i didn't consider rand() function, sorry.
So i close the pull request and open a new one.

**Comment by siidney** [comment]
It's cool. Tbh a lot of the 'mistakes' are left there intentionally, the missing const in function declarations etc, to prevent students copying the solutions verbatim. That's probably why the +1 in the rand was there.Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [siidney/Cpp-How-To-Program-9E] Update ex_1811.cpp (#17)From: hani361 To: siidney/Cpp-How-To-Program-9E CC: Siidney Watson ,Comment Good point 👍 Yes,you're right, i didn't consider rand() function, sorry.
So i close the pull request and open a new one.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/siidney/Cpp-How-To-Program-9E","title":"siidney/Cpp-How-To-Program-9E","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/siidney/Cpp-How-To-Program-9E"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hani361 in #17: Good point :+1: Yes,you're right, i didn't consider rand() function, sorry.\r\nSo i close the pull request and open a new one."}],"action":{"name":"View Pull Request","url":"https://github.com/siidney/Cpp-How-To-Program-9E/pull/17#issuecomment-364037561"}}}

**Pull request closed without merging**
